/* AURA — créditos de las imágenes (generado por creditos-js.mjs; no editar a mano).
   Todas las fotos tienen licencia libre y se han recortado y ajustado de tono para el sitio;
   en las marcadas como retocadas se han borrado logotipos o textos de la pantalla. */
window.AURA_CREDITS = [
  {
    "slot": "acerca-accesibilidad",
    "descripcion": "Dos manos sostienen un auraPhone y un dedo se acerca al teclado de la pantalla, sobre fondo oscuro",
    "autor": "freestocks",
    "autorUrl": "https://unsplash.com/@freestocks",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/fotografia-de-enfoque-selectivo-de-una-persona-usando-un-telefono-inteligente-mw6Onwg4frY",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "acerca-hero",
    "descripcion": "Edificio de techo circular de noche, con un anillo de luz azulada que recorre todo su borde",
    "autor": "Declan Sun",
    "autorUrl": "https://unsplash.com/@declansun",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-edificio-con-un-techo-circular-y-un-reloj-en-el--nNbLVA_9A4",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "acerca-historia",
    "descripcion": "Un ordenador antiguo de color beige, con monitor de tubo y teclado integrado, iluminado en la penumbra",
    "autor": "Callum Mullin",
    "autorUrl": "https://unsplash.com/@cmbgraphicdesign",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-ordenador-antiguo-se-asienta-sobre-una-superficie-estampada-J1yATCIy4PQ",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "acerca-newsroom-1",
    "descripcion": "Vista aérea de una planta solar que refleja la luz dorada del atardecer bajo un cielo con nubes",
    "autor": "Bernd 📷 Dittrich",
    "autorUrl": "https://unsplash.com/@hdbernd",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/planta-solar-en-un-paisaje-rural-bheTycKOh9Q",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "acerca-newsroom-2",
    "descripcion": "Un procesador visto por su cara de contactos dorados, apoyado sobre una superficie negra",
    "autor": "Daniel Pantu",
    "autorUrl": "https://unsplash.com/@danielpantu",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-primer-plano-de-un-chip-de-computadora-en-una-mesa-hoj771jnCB0",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "acerca-newsroom-3",
    "descripcion": "El módulo de triple cámara de un auraPhone Pro negro surge de la oscuridad con un destello de luz",
    "autor": "David Hurley",
    "autorUrl": "https://unsplash.com/@davidhurley",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/iphone-11-pro-max-negro-04952tJG5i8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "acerca-oportunidades",
    "descripcion": "Un equipo revisa diseños de pantallas en un portátil, ante una estantería iluminada con luz cálida",
    "autor": "Nasik Lababan",
    "autorUrl": "https://unsplash.com/@nasik",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/la-gente-esta-trabajando-en-una-computadora-portatil-en-una-oficina-moderna-Mgjum08dZx8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "acerca-proveedores",
    "descripcion": "Primer plano de una placa base azul oscuro sin componentes, con pistas y contactos dorados",
    "autor": "Vishnu Mohanan",
    "autorUrl": "https://unsplash.com/@vishnumaiea",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/primer-plano-de-placa-de-circuito-azul-oscuro-pfR18JNEMv8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurabook-air-15",
    "descripcion": "auraBook Air entreabierto, con la pantalla rosa, naranja y azul iluminando el teclado en la oscuridad",
    "autor": "Tanmoy Roy",
    "autorUrl": "https://unsplash.com/@tanmoy_roy",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/macbook-pro-en-superficie-negra-LAqL2IzNoF0",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurabook-ecosistema",
    "descripcion": "Un auraBook Pro junto a un monitor con un editor de vídeo, en un escritorio a oscuras con lámpara, teclado y ratón",
    "autor": "Sou Jest",
    "autorUrl": "https://unsplash.com/@soujest",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/portatil-y-monitor-en-un-espacio-de-trabajo-oscuro-EBCVK7UUaNY",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurabook-hero",
    "descripcion": "auraBook Pro entreabierto en la oscuridad; su pantalla tiñe de cian y naranja el teclado y la mesa",
    "autor": "Ales Nesetril",
    "autorUrl": "https://unsplash.com/@alesnesetril",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/computadora-portatil-gris-y-negra-en-surface-Im7lZjxeLhg",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurabook-perfil-desarrollo",
    "descripcion": "Un auraBook Pro con código y una consola abiertos en la pantalla, sobre un escritorio en penumbra",
    "autor": "AltumCode",
    "autorUrl": "https://unsplash.com/@altumcode",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/macbook-pro-abierto-cerca-de-una-taza-negra-de-canon-P2SkP_PXhlU",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurabook-perfil-estudios",
    "descripcion": "Un estudiante de espaldas, con auriculares, toma apuntes con un lápiz junto a su auraBook en una biblioteca antigua",
    "autor": "Tat Linh Nguyen",
    "autorUrl": "https://unsplash.com/@niko_nguyen_10",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/persona-estudiando-en-un-largo-escritorio-de-madera-en-la-biblioteca-SFUgDVSkfUM",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurabook-perfil-fotografia",
    "descripcion": "Un auraBook con un bosque entre niebla en la pantalla, entre dos velas encendidas en una sala en penumbra",
    "autor": "James McKinven",
    "autorUrl": "https://unsplash.com/@jmckinven",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/computadora-portatil-macbook-encendida-B3FwR-Hf9w8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurabook-perfil-musica",
    "descripcion": "Un auraBook Pro con un secuenciador musical, un controlador de pads iluminados, un altavoz de estudio y auriculares",
    "autor": "Erwi",
    "autorUrl": "https://unsplash.com/@erwimadethis",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/una-computadora-portatil-encima-de-un-escritorio-rt8nASaIQZA",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurabook-perfil-video",
    "descripcion": "Montaje de vídeo con varias pistas y ruedas de color en un portátil de teclado retroiluminado, a oscuras",
    "autor": "Peter Stumpf",
    "autorUrl": "https://unsplash.com/@peter_s",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/ordenador-portatil-negro-FhZEpxtTI_Y",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurabook-pro-14",
    "descripcion": "auraBook Pro entreabierto en tres cuartos, con un atardecer en la pantalla y un halo cian sobre la mesa",
    "autor": "Aashish Yadav",
    "autorUrl": "https://unsplash.com/@aashish_27",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-portatil-con-luz-roja-mpU2mzGR0Dg",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurabook-pro-16",
    "descripcion": "auraBook Pro entreabierto de frente, con el teclado bañado en luz violeta y azul de la pantalla, sobre negro",
    "autor": "Nikolay",
    "autorUrl": "https://unsplash.com/@beautyoftech",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/macbook-pro-encendido-sobre-superficie-blanca-DUfkXRwGQm8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurapad-accesorios-pencil",
    "descripcion": "Mano dibujando un boceto con AURA Pencil sobre la pantalla blanca de un auraPad, en un escritorio oscuro con una taza",
    "autor": "Kelly Sikkema",
    "autorUrl": "https://unsplash.com/@kellysikkema",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/persona-sosteniendo-un-ipad-blanco-con-funda-negra-2d-ZQjDhH94",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurapad-accesorios-teclado",
    "descripcion": "auraPad Air con Magic Keyboard negro y AURA Pencil acoplado arriba, con ondas azules en la pantalla de bloqueo",
    "autor": "Ernest Ojeh",
    "autorUrl": "https://unsplash.com/@namzo",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/tableta-negra-con-teclado-xSUZWZkjklc",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "aurapad-air-13-gris-espacial",
    "descripcion": "auraPad Air gris espacial de espaldas, inclinado y flotando sobre fondo negro",
    "autor": "Sayan Majhi",
    "autorUrl": "https://unsplash.com/@minimalsayan",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/macbook-plateado-sobre-superficie-negra-YKgTfX2n6iI",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "aurapad-air-13",
    "descripcion": "auraPad Air azul de espaldas, en vertical, con la cámara en la esquina, sobre fondo negro",
    "autor": "Jaime Marrero",
    "autorUrl": "https://unsplash.com/@jaimemarrero",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-ipad-azul-sentado-encima-de-una-mesa-de-madera-7hj8XxlYlOg",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "aurapad-crear-estudiar",
    "descripcion": "Mano con anillos subrayando con AURA Pencil un texto en la pantalla de un auraPad, en penumbra",
    "autor": "Salomé Watel",
    "autorUrl": "https://unsplash.com/@samefaisrire",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/hombre-sosteniendo-un-lapiz-de-manzana-4wY6p2F2jeE",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurapad-crear-ilustrar",
    "descripcion": "auraPad Pro con una ilustración de un gato atigrado a medio colorear y AURA Pencil al lado, sobre una alfombra oscura",
    "autor": "Syarafina Idris",
    "autorUrl": "https://unsplash.com/@mynameisfina",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/tableta-negra-con-estuche-con-estampado-de-cebra-dCeWUxnIYaM",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurapad-crear-medir",
    "descripcion": "Primer plano de la parte trasera de un auraPad Pro gris espacial, con doble cámara, flash y escáner LiDAR",
    "autor": "Thai Nguyen",
    "autorUrl": "https://unsplash.com/@quangthai_itshop",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/interfaz-grafica-del-usuario-I4XoCArS2IU",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurapad-crear-trabajar",
    "descripcion": "auraPad Pro acoplado a un Magic Keyboard blanco que lo sostiene en el aire, sobre una mesa oscura junto a una planta",
    "autor": "Mathieu Improvisato",
    "autorUrl": "https://unsplash.com/@matoovisato",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/una-computadora-portatil-sentada-encima-de-una-mesa-de-madera-7P2eZVar0Nw",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurapad-crear-video",
    "descripcion": "Manos sujetando un auraPad Pro con una app de edición de vídeo y su línea de tiempo, mientras eligen un clip con AURA Pencil",
    "autor": "Sirisvisual",
    "autorUrl": "https://unsplash.com/@sirisvisual",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/persona-sosteniendo-una-tableta-negra-g9jLj8Q3hhI",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "aurapad-hero",
    "descripcion": "auraPad Pro inclinado flotando sobre fondo negro, con un bosque otoñal visto desde el aire en la pantalla de bloqueo",
    "autor": "Sayan Majhi",
    "autorUrl": "https://unsplash.com/@minimalsayan",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/telefono-inteligente-android-negro-sobre-mesa-negra-qAMEcRuPoJo",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "aurapad-pro-11",
    "descripcion": "auraPad Pro gris espacial de espaldas e inclinado, con su módulo de cámaras, sobre fondo negro",
    "autor": "Romson Preechawit",
    "autorUrl": "https://unsplash.com/@woodies11",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/una-computadora-portatil-sentada-encima-de-una-mesa-blanca-_k5Kc6CdnwM",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "aurapad-pro-13",
    "descripcion": "auraPad Pro de frente con una pantalla de curvas naranjas, rojas, azules y violetas, sobre fondo negro",
    "autor": "Valen Don",
    "autorUrl": "https://unsplash.com/@thelasttime",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-primer-plano-de-una-tableta-sobre-una-mesa-A1V4vwaYJoU",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "aurapad-pro",
    "descripcion": "auraPad Pro con fondo de pantalla rojo y cian sobre piedra oscura, con AURA Pencil al lado bajo una luz rasante",
    "autor": "Francois  Hoang",
    "autorUrl": "https://unsplash.com/@aoirostudio",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/ipad-negro-con-lapiz-optico-blanco-gYVNvRygCUw",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "auraphone-18-pro-max",
    "descripcion": "Dos auraPhone 18 Pro Max de titanio, de frente y de espaldas, flotando sobre negro con un reflejo rojizo",
    "autor": "Faded_Gallery",
    "autorUrl": "https://unsplash.com/@faded_gallery",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-primer-plano-de-un-telefono-celular-con-una-camara-W78mZFcoArA",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "auraphone-18-pro",
    "descripcion": "auraPhone 18 Pro azul tumbado de espaldas, con su triple cámara, sobre fondo negro",
    "autor": "Faded_Gallery",
    "autorUrl": "https://unsplash.com/@faded_gallery",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-primer-plano-de-un-telefono-apple-con-una-camara-7s9wavvwDH8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "auraphone-destacado-1",
    "descripcion": "Mano a contraluz sosteniendo un auraPhone con la pantalla de bloqueo azul brillante al anochecer",
    "autor": "Nils Benyamin",
    "autorUrl": "https://unsplash.com/@nilsbenyamin",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/una-persona-sosteniendo-un-telefono-celular-en-la-mano-Q5xCgXvhaII",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "auraphone-destacado-2",
    "descripcion": "Cargador MagSafe plateado sobre un soporte de aluminio, junto a las cámaras de un auraPhone, sobre fondo negro",
    "autor": "Studio Proper",
    "autorUrl": "https://unsplash.com/@studioproper",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/marco-de-plastico-redondo-blanco-sobre-mesa-negra-CWWa6f1EB5g",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "auraphone-destacado-3",
    "descripcion": "auraPhone Duo abierto con la pantalla de inicio y un fondo de trazos azules, de pie sobre una mesa en penumbra",
    "autor": "Amanz",
    "autorUrl": "https://unsplash.com/@amanz",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/interfaz-grafica-de-usuario-aplicacion-vh6MI3fev5c",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "auraphone-destacado-4",
    "descripcion": "Gotas de agua sobre la pantalla de un auraPhone negro apoyado en una tarima de madera mojada",
    "autor": "Shuvro Mojumder",
    "autorUrl": "https://unsplash.com/@shuvrosettledown",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/telefono-inteligente-negro-sobre-superficie-de-madera-marron-d2Zc6G6y5H4",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "auraphone-destacado-5",
    "descripcion": "Conector USB-C de un cable claro en primer plano, sobre fondo negro",
    "autor": "Mishaal Zahed (Meschael Zahède)",
    "autorUrl": "https://unsplash.com/@mishaalzahed",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/cable-usb-blanco-sobre-superficie-negra-dYocS1QjjvI",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "auraphone-destacado-6",
    "descripcion": "Mano acercando un auraPhone negro a un datáfono con el símbolo de pago sin contacto",
    "autor": "Jonas Leupe",
    "autorUrl": "https://unsplash.com/@jonasleupe",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/mujer-sosteniendo-un-telefono-inteligente-android-0IVop5v4MMU",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "auraphone-duo",
    "descripcion": "auraPhone Duo plateado entreabierto en vertical, con su triple cámara, sobre fondo negro",
    "autor": "Amanz",
    "autorUrl": "https://unsplash.com/@amanz",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-primer-plano-de-un-telefono-celular-sobre-una-mesa--PALKeQhf2c",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "auraphone-hero",
    "descripcion": "Parte trasera de un auraPhone plateado con triple cámara, centrado sobre fondo negro",
    "autor": "ubeyonroad",
    "autorUrl": "https://unsplash.com/@ubeyonroad",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/parte-trasera-de-un-smartphone-plateado-con-tres-camaras-oLZ2htMNhbA",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "auraphone-zoom-1",
    "descripcion": "Primer plano del módulo de triple cámara de un auraPhone en gris oscuro, sobre fondo negro",
    "autor": "Branislav Rodman",
    "autorUrl": "https://unsplash.com/@branislavrodman",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-primer-plano-de-un-telefono-celular-con-un-fondo-negro-Bt_Nds4n7UY",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "auraphone-zoom-2",
    "descripcion": "Silueta de un faro con la linterna encendida al anochecer, con el horizonte naranja y el cielo azul oscuro",
    "autor": "Tim Foster",
    "autorUrl": "https://unsplash.com/@timberfoster",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/silueta-del-faro-al-atardecer-luyqrtZaWmg",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "auraphone-zoom-3",
    "descripcion": "Parte superior de un auraPhone con la Dynamic Island y la pantalla de bloqueo violeta, sobre fondo negro",
    "autor": "Fujiphilm",
    "autorUrl": "https://unsplash.com/@fujiphilm",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-telefono-celular-con-una-pantalla-purpura-YhDDmc_nW80",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "auraphone-zoom-4",
    "descripcion": "Interior de un teléfono desmontado con la placa térmica de cobre y pasta azul sobre el procesador",
    "autor": "Sandeep",
    "autorUrl": "https://unsplash.com/@adeveloper79",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/smartphone-desmontado-que-revela-componentes-electronicos-internos-l1uzgDexxd4",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "inicio-acerca",
    "descripcion": "Fachada de cristal azul de un edificio de oficinas de noche, con varias plantas iluminadas en luz cálida",
    "autor": "Jahanzeb Ahsan",
    "autorUrl": "https://unsplash.com/@jahan_photobox",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/ventanas-de-edificios-de-oficinas-iluminadas-por-la-noche-Xqb8MqNS8hc",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "inicio-hero-aurabook",
    "descripcion": "auraBook entreabierto en la oscuridad, con el teclado bañado por la luz rosa y azul de su pantalla",
    "autor": "Hostaphoto",
    "autorUrl": "https://unsplash.com/@hostaphoto",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/ordenador-portatil-negro-y-morado-GsXszN5AokQ",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "inicio-hero-aurapad",
    "descripcion": "auraPad sobre fondo negro con la pantalla de bloqueo encendida, que muestra un edificio de cristal de noche",
    "autor": "Sayan Majhi",
    "autorUrl": "https://unsplash.com/@minimalsayan",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-telefono-celular-con-una-imagen-de-un-edificio-en-la-pantalla-LJejlC5Y1xs",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "inicio-hero-auraphone",
    "descripcion": "auraPhone Duo plateado abierto en una mano, con su triple cámara y la pantalla apagada, sobre fondo negro",
    "autor": "Onur Binay",
    "autorUrl": "https://unsplash.com/@onurbinay",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/persona-sosteniendo-un-telefono-inteligente-android-blanco-sPxk3zxpQ08",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "inicio-novedad-aurabook-air",
    "descripcion": "auraBook plateado flotando en el aire sobre fondo negro, visto desde abajo con la tapa abierta",
    "autor": "Dima Solomin",
    "autorUrl": "https://unsplash.com/@solomin",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-ordenador-apple-vuela-por-los-aires-8bgkFqrG-aQ",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "inicio-novedad-aurapad-air",
    "descripcion": "auraPad flotando sobre fondo negro, con un fondo de pantalla de abanicos de luz azules y naranjas",
    "autor": "David Švihovec",
    "autorUrl": "https://unsplash.com/@iamdavid_10",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/ipad-negro-sobre-mesa-blanca-pb_s0FYQZOo",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "inicio-novedad-camara",
    "descripcion": "Dos auraPhone 18 Pro de espaldas, en titanio azul y blanco, sobre un fondo azul en penumbra",
    "autor": "Amanz",
    "autorUrl": "https://unsplash.com/@amanz",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/dos-iphones-sentados-uno-al-lado-del-otro-sobre-una-mesa-uumtSKNTjss",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "inicio-novedad-teleobjetivo",
    "descripcion": "Primer plano del módulo de tres cámaras de un auraPhone Pro de titanio, sobre fondo negro",
    "autor": "Samuel Angor",
    "autorUrl": "https://unsplash.com/@sammysays___",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-primer-plano-de-un-telefono-celular-sobre-una-mesa-RPiEdud0dcw",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "inicio-trade-in",
    "descripcion": "Un smartphone desmontado, con los componentes internos a la vista, sobre una mesa azul oscuro",
    "autor": "Sandeep",
    "autorUrl": "https://unsplash.com/@adeveloper79",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-smartphone-desmontado-con-sus-componentes-internos-expuestos-x243E3Re1Q4",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "soporte-contacto",
    "descripcion": "Vista cenital de un especialista que atiende a un cliente junto a una mesa de madera clara con un auraPad expositor",
    "autor": "amandazi photography",
    "autorUrl": "https://unsplash.com/@amandazi_photography",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-empleado-de-tienda-ayuda-a-un-cliente-en-un-mostrador-DUWvgrJ2P-8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true
  },
  {
    "slot": "trade-in-hero",
    "descripcion": "El módulo de triple cámara de un auraPhone negro nuevo asoma de su caja abierta sobre fondo negro",
    "autor": "Rohan Krishnan",
    "autorUrl": "https://unsplash.com/@rohankrishnann",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-iphone-en-una-caja-sobre-un-fondo-negro-lkizfYW3ohw",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  },
  {
    "slot": "trade-in-reciclaje",
    "descripcion": "Un teléfono abierto deja ver el chasis, la batería y los circuitos sobre una superficie oscura",
    "autor": "Sandeep",
    "autorUrl": "https://unsplash.com/@adeveloper79",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/componentes-internos-de-un-smartphone-desmontado-sobre-una-superficie-oscura--PZRsFHDQQk",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false
  }
];
