/* AURA — créditos de las imágenes (generado por creditos-js.mjs; no editar a mano).
   Todas las fotos tienen licencia libre y se han recortado y ajustado de tono para el sitio;
   en las marcadas como retocadas se han borrado logotipos o textos de la pantalla. */
window.AURA_CREDITS = [
  {
    "slot": "acerca-accesibilidad",
    "tipo": "foto",
    "media": "img/acerca-accesibilidad.webp",
    "descripcion": "Dos manos sostienen un auraPhone y un dedo se acerca al teclado de la pantalla, sobre fondo oscuro",
    "autor": "freestocks",
    "autorUrl": "https://unsplash.com/@freestocks",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/fotografia-de-enfoque-selectivo-de-una-persona-usando-un-telefono-inteligente-mw6Onwg4frY",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "acerca-hero",
    "tipo": "foto",
    "media": "img/acerca-hero.webp",
    "descripcion": "Edificio de techo circular de noche, con un anillo de luz azulada que recorre todo su borde",
    "autor": "Declan Sun",
    "autorUrl": "https://unsplash.com/@declansun",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-edificio-con-un-techo-circular-y-un-reloj-en-el--nNbLVA_9A4",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "acerca-historia",
    "tipo": "foto",
    "media": "img/acerca-historia.webp",
    "descripcion": "Un ordenador antiguo de color beige, con monitor de tubo y teclado integrado, iluminado en la penumbra",
    "autor": "Callum Mullin",
    "autorUrl": "https://unsplash.com/@cmbgraphicdesign",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-ordenador-antiguo-se-asienta-sobre-una-superficie-estampada-J1yATCIy4PQ",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "acerca-newsroom-1",
    "tipo": "foto",
    "media": "img/acerca-newsroom-1.webp",
    "descripcion": "Vista aérea de una planta solar que refleja la luz dorada del atardecer bajo un cielo con nubes",
    "autor": "Bernd 📷 Dittrich",
    "autorUrl": "https://unsplash.com/@hdbernd",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/planta-solar-en-un-paisaje-rural-bheTycKOh9Q",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "acerca-newsroom-2",
    "tipo": "foto",
    "media": "img/acerca-newsroom-2.webp",
    "descripcion": "Un procesador visto por su cara de contactos dorados, apoyado sobre una superficie negra",
    "autor": "Daniel Pantu",
    "autorUrl": "https://unsplash.com/@danielpantu",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-primer-plano-de-un-chip-de-computadora-en-una-mesa-hoj771jnCB0",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "acerca-newsroom-3",
    "tipo": "foto",
    "media": "img/acerca-newsroom-3.webp",
    "descripcion": "El módulo de triple cámara de un auraPhone Pro negro surge de la oscuridad con un destello de luz",
    "autor": "David Hurley",
    "autorUrl": "https://unsplash.com/@davidhurley",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/iphone-11-pro-max-negro-04952tJG5i8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "acerca-oportunidades",
    "tipo": "foto",
    "media": "img/acerca-oportunidades.webp",
    "descripcion": "Un equipo revisa diseños de pantallas en un portátil, ante una estantería iluminada con luz cálida",
    "autor": "Nasik Lababan",
    "autorUrl": "https://unsplash.com/@nasik",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/la-gente-esta-trabajando-en-una-computadora-portatil-en-una-oficina-moderna-Mgjum08dZx8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "acerca-proveedores",
    "tipo": "foto",
    "media": "img/acerca-proveedores.webp",
    "descripcion": "Primer plano de una placa base azul oscuro sin componentes, con pistas y contactos dorados",
    "autor": "Vishnu Mohanan",
    "autorUrl": "https://unsplash.com/@vishnumaiea",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/primer-plano-de-placa-de-circuito-azul-oscuro-pfR18JNEMv8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurabook-air-15-azul-cielo",
    "tipo": "foto",
    "media": "img/aurabook-air-15-azul-cielo.webp",
    "descripcion": "auraBook Air en azul cielo abierto sobre negro, con teclado negro y la pantalla de ondas turquesa",
    "autor": "Kyu3a",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Kyu3a",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:M5_Macbook_Air_13_Sky_Blue_model.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Recortado sobre negro; pantalla (apagada en el original) con un fondo generado; conector borrado."
  },
  {
    "slot": "aurabook-air-15-blanco-estrella",
    "tipo": "foto",
    "media": "img/aurabook-air-15-blanco-estrella.webp",
    "descripcion": "auraBook Air 15″ en blanco estrella abierto sobre negro, con la pantalla de ondas turquesa",
    "autor": "KKPCW (Kyu3)",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:KKPCW",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Macbook_Air_15_inch_-_1.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Recortado sobre negro; pantalla sustituida por un fondo generado; conector borrado."
  },
  {
    "slot": "aurabook-air-15-medianoche",
    "tipo": "foto",
    "media": "img/aurabook-air-15-medianoche.webp",
    "descripcion": "auraBook Air 15″ en color medianoche abierto sobre negro, con la pantalla de ondas turquesa",
    "autor": "KKPCW (Kyu3)",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:KKPCW",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Macbook_Air_15_inch_-_3.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Recortado sobre negro; pantalla sustituida por un fondo generado; cable borrado."
  },
  {
    "slot": "aurabook-air-15",
    "tipo": "foto",
    "media": "img/aurabook-air-15.webp",
    "descripcion": "auraBook Air 15″ plateado, fino y abierto sobre negro, con la pantalla de ondas turquesa",
    "autor": "AzureSaturn",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:AzureSaturn",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:MacBook_Air_(15-inch,_M4,_Silver).jpg",
    "licencia": "CC0 1.0",
    "licenciaUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Recortado sobre negro; pantalla sustituida por un fondo generado."
  },
  {
    "slot": "aurabook-bateria",
    "tipo": "foto",
    "media": "img/aurabook-bateria.webp",
    "descripcion": "auraBook Pro abierto en la oscuridad, enchufado con el piloto de carga encendido y la pantalla rosa y dorada",
    "autor": "SimonWaldherr",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:SimonWaldherr",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_MacBook_Pro_16%22_M2_Max_5.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla sustituida por un fondo generado; reflejo de iconos borrado."
  },
  {
    "slot": "aurabook-chip",
    "tipo": "foto",
    "media": "img/aurabook-chip.webp",
    "descripcion": "Chip AURA Silicon con cuatro módulos de memoria, en perspectiva sobre negro con un canto dorado",
    "autor": "Henriok",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Henriok",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_M1_Max.png",
    "licencia": "CC0 1.0",
    "licenciaUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Logotipo y textos grabados borrados; girada y colocada en perspectiva sobre negro."
  },
  {
    "slot": "aurabook-diseno",
    "tipo": "foto",
    "media": "img/aurabook-diseno.webp",
    "descripcion": "Perfil de un auraBook Pro casi cerrado, con el teclado iluminado por el brillo de la pantalla",
    "autor": "SimonWaldherr",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:SimonWaldherr",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_MacBook_Pro_16%22_M2_Max_illuminated.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurabook-ecosistema",
    "tipo": "foto",
    "media": "img/aurabook-ecosistema.webp",
    "descripcion": "auraBook Pro abierto entre unos auriculares de diadema y un ratón, bañados por una luz cálida en la penumbra",
    "autor": "SimonWaldherr",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:SimonWaldherr",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_MacBook_Pro_16%22_M2_Max_with_Headset_and_Mouse.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Reflejos de texto de la pantalla borrados."
  },
  {
    "slot": "aurabook-medio-ambiente",
    "tipo": "foto",
    "media": "img/aurabook-medio-ambiente.webp",
    "descripcion": "Hoja de helecho verde intenso sobre un fondo casi negro",
    "autor": "Rowan Heuvel",
    "autorUrl": "https://unsplash.com/@insolitus",
    "fuente": "Wikimedia Commons (Unsplash)",
    "url": "https://commons.wikimedia.org/wiki/File:Fern_Leaf_(Unsplash).jpg",
    "licencia": "CC0 1.0",
    "licenciaUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurabook-pantalla",
    "tipo": "foto",
    "media": "img/aurabook-pantalla.webp",
    "descripcion": "auraBook Pro abierto en la oscuridad, con ondas de luz naranjas, rosas y violetas en la pantalla, bajo la muesca de la cámara",
    "autor": "SimonWaldherr",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:SimonWaldherr",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_MacBook_Pro_16%22_M2_Max_2.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla sustituida por un fondo AURA generado por código, con la muesca de la cámara."
  },
  {
    "slot": "aurabook-perfil-desarrollo",
    "tipo": "foto",
    "media": "img/aurabook-perfil-desarrollo.webp",
    "descripcion": "auraBook Pro con un editor de código y una terminal en pantalla, bajo una luz roja y naranja",
    "autor": "SimonWaldherr",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:SimonWaldherr",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_MacBook_Pro_16%22_M2Max.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla sustituida por un editor de código generado."
  },
  {
    "slot": "aurabook-perfil-estudios",
    "tipo": "foto",
    "media": "img/aurabook-perfil-estudios.webp",
    "descripcion": "Un estudiante de espaldas, con auriculares, toma apuntes con un lápiz junto a su auraBook en una biblioteca antigua",
    "autor": "Tat Linh Nguyen",
    "autorUrl": "https://unsplash.com/@niko_nguyen_10",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/persona-estudiando-en-un-largo-escritorio-de-madera-en-la-biblioteca-SFUgDVSkfUM",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurabook-perfil-fotografia",
    "tipo": "foto",
    "media": "img/aurabook-perfil-fotografia.webp",
    "descripcion": "auraBook Pro abierto junto a una cámara sin espejo con objetivo zoom, en un escritorio en penumbra",
    "autor": "SimonWaldherr",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:SimonWaldherr",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_MacBook_Pro_16%22_M2_Max_and_Nikon_Z6.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla sustituida por un fondo generado; marca de la cámara borrada."
  },
  {
    "slot": "aurabook-perfil-musica",
    "tipo": "foto",
    "media": "img/aurabook-perfil-musica.webp",
    "descripcion": "auraBook Pro abierto en la penumbra, con un secuenciador de audio en la pantalla: siete pistas de colores y el mezclador, bajo una luz azul",
    "autor": "SimonWaldherr",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:SimonWaldherr",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_MacBook_Pro_16%22_M2_Max_3.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla sustituida por un secuenciador de audio generado por código (con la muesca de la cámara)."
  },
  {
    "slot": "aurabook-perfil-video",
    "tipo": "foto",
    "media": "img/aurabook-perfil-video.webp",
    "descripcion": "auraBook Pro abierto junto a un dron plegado, con un montaje de vídeo 8K en la pantalla: el visor con un atardecer y la línea de tiempo con sus clips",
    "autor": "SimonWaldherr",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:SimonWaldherr",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_MacBook_Pro_16%22_M2_Max_with_Drone.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla sustituida por un editor de vídeo generado por código (con la muesca de la cámara); marca del dron y reflejo de la pantalla antigua en la mesa borrados."
  },
  {
    "slot": "aurabook-pro-14-plata",
    "tipo": "foto",
    "media": "img/aurabook-pro-14-plata.webp",
    "descripcion": "auraBook Pro 14″ plateado visto de frente sobre negro, con teclado negro y la pantalla de ondas violetas",
    "autor": "Oops4321",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Oops4321",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:A_2021_14-inch_Silver_MacBook_Pro.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Recortado sobre negro; pantalla sustituida por un fondo generado."
  },
  {
    "slot": "aurabook-pro-14",
    "tipo": "foto",
    "media": "img/aurabook-pro-14.webp",
    "descripcion": "auraBook Pro 14″ en negro espacial abierto sobre negro, con la pantalla de ondas ámbar y rosa",
    "autor": "AzureSaturn",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:AzureSaturn",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:MacBook_Pro_(14-inch,_M5,_Space_Black).jpg",
    "licencia": "CC0 1.0",
    "licenciaUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Recortado sobre negro; pantalla sustituida por un fondo generado; conector y cables borrados."
  },
  {
    "slot": "aurabook-pro-16",
    "tipo": "foto",
    "media": "img/aurabook-pro-16.webp",
    "descripcion": "auraBook Pro 16″ plateado abierto sobre negro, con teclado negro y la pantalla con ondas azules y violetas",
    "autor": "AzureSaturn",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:AzureSaturn",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:MacBook_Pro_(16-inch,_M4_Pro,_Silver).jpg",
    "licencia": "CC0 1.0",
    "licenciaUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Recortado sobre negro; pantalla sustituida por un fondo generado; conector y cables borrados."
  },
  {
    "slot": "aurabook-puertos",
    "tipo": "foto",
    "media": "img/aurabook-puertos.webp",
    "descripcion": "Lateral de un auraBook Pro con ranura para tarjetas SD, puerto USB-C y HDMI bajo una luz cálida",
    "autor": "SimonWaldherr",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:SimonWaldherr",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_MacBook_Pro_16%22_M2_Max_closeup.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Iconos de la pantalla borrados."
  },
  {
    "slot": "aurabook-teclado",
    "tipo": "foto",
    "media": "img/aurabook-teclado.webp",
    "descripcion": "Primer plano del teclado negro de un auraBook Pro junto al trackpad, en penumbra",
    "autor": "Gyasi Linje",
    "autorUrl": "",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_Macbook_Pro_14%22_2021_-_Keyboard.png",
    "licencia": "CC BY 3.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by/3.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "aurapad-accesorio-funda",
    "tipo": "foto",
    "media": "img/aurapad-accesorio-funda.webp",
    "descripcion": "Funda Folio azul cerrada sobre un auraPad, de frente y en ligera perspectiva, sobre fondo negro",
    "autor": "Daniel Romero",
    "autorUrl": "https://unsplash.com/@rmrdnl",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/estuche-inteligente-azul-sobre-mesa-blanca-WcwRqDBCrpA",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-accesorios-pencil",
    "tipo": "foto",
    "media": "img/aurapad-accesorios-pencil.webp",
    "descripcion": "AURA Pencil Pro al final de un trazo dorado recién dibujado en la pantalla de un auraPad Pro, en perspectiva sobre fondo negro",
    "autor": "Jtosman",
    "autorUrl": "https://commons.wikimedia.org/wiki/Special:ListFiles/Jtosman",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:ApplePencilPro2.png",
    "licencia": "CC0",
    "licenciaUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-accesorios-pencil",
    "tipo": "foto",
    "media": "img/aurapad-accesorios-pencil.webp",
    "descripcion": "AURA Pencil Pro al final de un trazo dorado recién dibujado en la pantalla de un auraPad Pro, en perspectiva sobre fondo negro",
    "autor": "Kyu3a",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Kyu3a",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:M4_iPad_Pro_series_-_2.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-accesorios-teclado",
    "tipo": "foto",
    "media": "img/aurapad-accesorios-teclado.webp",
    "descripcion": "auraPad Pro acoplado a un Magic Keyboard blanco, abierto como un portátil, con ondas de luz azules y violetas en la pantalla",
    "autor": "Kyu3a",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Kyu3a",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:M4_iPad_Pro_series_-_2.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla sustituida por un fondo AURA generado por código (ondas azules); cable y motas borrados."
  },
  {
    "slot": "aurapad-air-13-blanco-estrella",
    "tipo": "foto",
    "media": "img/aurapad-air-13-blanco-estrella.webp",
    "descripcion": "Trasera blanco estrella del auraPad Air 13″, con su única cámara en la esquina, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPad_Air_11-inch_(M2)_back_side_(20250525_154602).jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-air-13-gris-espacial",
    "tipo": "foto",
    "media": "img/aurapad-air-13-gris-espacial.webp",
    "descripcion": "Trasera gris espacial del auraPad Air 13″, con su única cámara en la esquina, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPad_Air_11-inch_(M2)_back_side_(20250525_154602).jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-air-13-purpura",
    "tipo": "foto",
    "media": "img/aurapad-air-13-purpura.webp",
    "descripcion": "Trasera púrpura del auraPad Air 13″, con su única cámara en la esquina, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPad_Air_11-inch_(M2)_back_side_(20250525_154602).jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-air-13",
    "tipo": "foto",
    "media": "img/aurapad-air-13.webp",
    "descripcion": "Trasera azul del auraPad Air 13″, con su única cámara en la esquina, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPad_Air_11-inch_(M2)_back_side_(20250525_154602).jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-bateria",
    "tipo": "foto",
    "media": "img/aurapad-bateria.webp",
    "descripcion": "Cable USB‑C blanco enrollado, con el conector en primer plano, sobre fondo negro",
    "autor": "Tony Webster",
    "autorUrl": "https://www.flickr.com/people/diversey/",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:USB_Type-C_Cable_-_iPad_USB-C_Charger_(45640822114).jpg",
    "licencia": "CC BY 2.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by/2.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-camaras",
    "tipo": "foto",
    "media": "img/aurapad-camaras.webp",
    "descripcion": "Módulo de cámaras de un auraPad Pro plateado, con el gran angular, el escáner LiDAR, el flash y el micrófono, sobre negro",
    "autor": "Kyu3a",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Kyu3a",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:M4_iPad_Pro_back_camera.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-chip",
    "tipo": "foto",
    "media": "img/aurapad-chip.webp",
    "descripcion": "Primer plano de la matriz de contactos de un chip sobre una placa oscura, con luz fría",
    "autor": "Akshat Sharma",
    "autorUrl": "https://unsplash.com/@asphotographypics",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/primer-plano-de-un-procesador-de-computadora-con-muchos-pines-GhLDc9jRKNw",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-crear-estudiar",
    "tipo": "foto",
    "media": "img/aurapad-crear-estudiar.webp",
    "descripcion": "Mano con anillos subrayando con AURA Pencil un texto en la pantalla de un auraPad, en penumbra",
    "autor": "Salomé Watel",
    "autorUrl": "https://unsplash.com/@samefaisrire",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/hombre-sosteniendo-un-lapiz-de-manzana-4wY6p2F2jeE",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-crear-ilustrar",
    "tipo": "foto",
    "media": "img/aurapad-crear-ilustrar.webp",
    "descripcion": "auraPad Pro con la ilustración de un gato atigrado a medio colorear y AURA Pencil al lado, sobre una alfombra oscura",
    "autor": "Syarafina Idris",
    "autorUrl": "https://unsplash.com/@mynameisfina",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/tableta-negra-con-estuche-con-estampado-de-cebra-dCeWUxnIYaM",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-crear-trabajar",
    "tipo": "foto",
    "media": "img/aurapad-crear-trabajar.webp",
    "descripcion": "auraPad Pro acoplado a un teclado blanco que lo sostiene en el aire, con ondas de luz ámbar en la pantalla, sobre una mesa oscura junto a una planta",
    "autor": "Mathieu Improvisato",
    "autorUrl": "https://unsplash.com/@matoovisato",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/una-computadora-portatil-sentada-encima-de-una-mesa-de-madera-7P2eZVar0Nw",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla sustituida por un fondo AURA generado por código; se conservan los reflejos de la ventana."
  },
  {
    "slot": "aurapad-crear-video",
    "tipo": "foto",
    "media": "img/aurapad-crear-video.webp",
    "descripcion": "Manos sujetando un auraPad Pro con una app de edición de vídeo abierta en su línea de tiempo, mientras eligen un clip con AURA Pencil",
    "autor": "Sirisvisual",
    "autorUrl": "https://unsplash.com/@sirisvisual",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/persona-sosteniendo-una-tableta-negra-g9jLj8Q3hhI",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true,
    "retoque": "Borrados de la pantalla la fecha y un rótulo en francés y el título de un vídeo que nombraba otra marca."
  },
  {
    "slot": "aurapad-diseno",
    "tipo": "foto",
    "media": "img/aurapad-diseno.webp",
    "descripcion": "Canto inferior finísimo de un auraPad plateado, con el puerto USB‑C y las rejillas de altavoz, sobre fondo negro",
    "autor": "Autor no indicado",
    "autorUrl": "",
    "fuente": "Pexels",
    "url": "https://www.pexels.com/photo/13570169/",
    "licencia": "Licencia de Pexels",
    "licenciaUrl": "https://www.pexels.com/license/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-hero",
    "tipo": "foto",
    "media": "img/aurapad-hero.webp",
    "descripcion": "Tres auraPad en abanico sobre fondo negro: un Air azul y un Pro plata de espaldas, detrás de un Pro de frente con una nebulosa en la pantalla",
    "autor": "Kyu3a",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Kyu3a",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:M4_iPad_Pro_series_-_2.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-hero",
    "tipo": "foto",
    "media": "img/aurapad-hero.webp",
    "descripcion": "Tres auraPad en abanico sobre fondo negro: un Air azul y un Pro plata de espaldas, detrás de un Pro de frente con una nebulosa en la pantalla",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPad_Air_11-inch_(M2)_back_side_(20250525_154602).jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-hero",
    "tipo": "foto",
    "media": "img/aurapad-hero.webp",
    "descripcion": "Tres auraPad en abanico sobre fondo negro: un Air azul y un Pro plata de espaldas, detrás de un Pro de frente con una nebulosa en la pantalla",
    "autor": "arnaud girault",
    "autorUrl": "https://unsplash.com/@arnaudastro",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-objeto-azul-en-forma-de-corazon-en-medio-del-cielo-VhKJHOz2tJ8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-hero",
    "tipo": "foto",
    "media": "img/aurapad-hero.webp",
    "descripcion": "Tres auraPad en abanico sobre fondo negro: un Air azul y un Pro plata de espaldas, detrás de un Pro de frente con una nebulosa en la pantalla",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPad_Pro_11-inch_backside.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-medio-ambiente",
    "tipo": "foto",
    "media": "img/aurapad-medio-ambiente.webp",
    "descripcion": "Fronda de helecho iluminada sobre fondo negro",
    "autor": "gunthercox",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Gunthercx",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Fern_Leaves_Black_Background.JPG",
    "licencia": "CC0",
    "licenciaUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-pantalla",
    "tipo": "foto",
    "media": "img/aurapad-pantalla.webp",
    "descripcion": "Pantalla de un auraPad Pro en tres cuartos con una nebulosa azul y ámbar llena de estrellas, sobre fondo negro",
    "autor": "Kyu3a",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Kyu3a",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:M4_iPad_Pro_series_-_2.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-pantalla",
    "tipo": "foto",
    "media": "img/aurapad-pantalla.webp",
    "descripcion": "Pantalla de un auraPad Pro en tres cuartos con una nebulosa azul y ámbar llena de estrellas, sobre fondo negro",
    "autor": "arnaud girault",
    "autorUrl": "https://unsplash.com/@arnaudastro",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/una-nebulosa-colorida-con-estrellas-en-el-espacio-profundo-BGOMkThbjwg",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-pro-11",
    "tipo": "foto",
    "media": "img/aurapad-pro-11.webp",
    "descripcion": "Trasera plateada del auraPad Pro 11″, con su módulo de cámaras y el escáner LiDAR en la esquina, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPad_Pro_11-inch_backside.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-pro-13-negro-espacial",
    "tipo": "foto",
    "media": "img/aurapad-pro-13-negro-espacial.webp",
    "descripcion": "Trasera negro espacial del auraPad Pro 13″, con el módulo de cámaras y el escáner LiDAR en la esquina, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPad_Pro_13-inch_backside.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-pro-13-plata",
    "tipo": "foto",
    "media": "img/aurapad-pro-13-plata.webp",
    "descripcion": "Trasera plateada del auraPad Pro 13″, con el módulo de cámaras y el escáner LiDAR en la esquina, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPad_Pro_13-inch_backside.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-pro-13-plata",
    "tipo": "foto",
    "media": "img/aurapad-pro-13-plata.webp",
    "descripcion": "Trasera plateada del auraPad Pro 13″, con el módulo de cámaras y el escáner LiDAR en la esquina, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPad_Pro_11-inch_backside.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "aurapad-pro-13",
    "tipo": "foto",
    "media": "img/aurapad-pro-13.webp",
    "descripcion": "auraPad Pro 13″ de frente sobre fondo negro, con la pantalla encendida: ondas de luz rosas, rojas y azules",
    "autor": "Kyu3a",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Kyu3a",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:M4_iPad_Pro_series_-_2.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla sustituida por un fondo AURA generado por código."
  },
  {
    "slot": "auraphone-18-pro-azul-glacial",
    "tipo": "foto",
    "media": "img/auraphone-18-pro-azul-glacial.webp",
    "descripcion": "auraPhone 18 Pro azul glacial de espaldas, con la meseta de cámaras de lado a lado, sobre fondo negro",
    "autor": "Kyu3a",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Kyu3a",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPhone_18_Pro_(Glacier_model)_-_4.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "auraphone-18-pro-max-plata",
    "tipo": "foto",
    "media": "img/auraphone-18-pro-max-plata.webp",
    "descripcion": "auraPhone 18 Pro Max plata de espaldas, con la meseta de cámaras de lado a lado, sobre fondo negro",
    "autor": "Ahmad Ali Karim",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:EmpAhmadK",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Silver_iPhone_17_Pro_Max_(cropped).jpg",
    "licencia": "CC0",
    "licenciaUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "auraphone-18-pro-max",
    "tipo": "foto",
    "media": "img/auraphone-18-pro-max.webp",
    "descripcion": "auraPhone 18 Pro Max burdeos de espaldas, con la meseta de cámaras de lado a lado, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPhone_18_Pro_Max_rear.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "auraphone-18-pro-plata",
    "tipo": "foto",
    "media": "img/auraphone-18-pro-plata.webp",
    "descripcion": "auraPhone 18 Pro plata de espaldas, con la meseta de cámaras de lado a lado, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPhone_17_Pro_Max.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "auraphone-18-pro",
    "tipo": "foto",
    "media": "img/auraphone-18-pro.webp",
    "descripcion": "auraPhone 18 Pro negro de espaldas, con la meseta de cámaras de lado a lado, sobre fondo negro",
    "autor": "Farragutful",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Farragutful",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPhone_18_Pro_-_black_01.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "auraphone-accesorio-cargador",
    "tipo": "foto",
    "media": "img/auraphone-accesorio-cargador.webp",
    "descripcion": "Cargador magnético plateado y blanco con su cable USB-C, sobre fondo negro",
    "autor": "James Tamim",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Jamestamim",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:MagSafe_and_USB-C_Cable_Charger_for_iPhone.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "auraphone-accesorio-funda",
    "tipo": "foto",
    "media": "img/auraphone-accesorio-funda.webp",
    "descripcion": "Funda de ante azul petróleo puesta en un auraPhone, con el hueco de la meseta de cámaras, sobre negro",
    "autor": "Masood Aslami",
    "autorUrl": "https://www.pexels.com/@masoodaslami",
    "fuente": "Pexels",
    "url": "https://www.pexels.com/photo/sleek-smartphone-case-on-wooden-surface-37669736/",
    "licencia": "Licencia de Pexels",
    "licenciaUrl": "https://www.pexels.com/license/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "auraphone-bateria",
    "tipo": "foto",
    "media": "img/auraphone-bateria.webp",
    "descripcion": "Dos auraPhone 18 Pro plata de espaldas sobre soportes de carga magnética, en penumbra",
    "autor": "Ahmad Ali Karim",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:EmpAhmadK",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPhone_17_launch_at_Apple_TRX_Malaysia_98.jpg",
    "licencia": "CC0",
    "licenciaUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "auraphone-camara-detalle",
    "tipo": "foto",
    "media": "img/auraphone-camara-detalle.webp",
    "descripcion": "Primer plano de la meseta de cámaras de un auraPhone 18 Pro Max burdeos: tres objetivos, flash y LiDAR",
    "autor": "Kyu3a",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Kyu3a",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Back_Camera_of_iPhone_18_Pro_Max.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "auraphone-chip",
    "tipo": "foto",
    "media": "img/auraphone-chip.webp",
    "descripcion": "Oblea de silicio en macro, con la rejilla de chips en reflejos iridiscentes de colores",
    "autor": "Laura Ockel",
    "autorUrl": "https://unsplash.com/@viazavier",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/oblea-de-silicio-con-rejilla-de-microchip-iridiscente-qOx9KsvpqcM",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "auraphone-destacado-2",
    "tipo": "foto",
    "media": "img/auraphone-destacado-2.webp",
    "descripcion": "Cargador magnético plateado sobre su soporte de aluminio en forma de anillo, encima de una mesa negra",
    "autor": "Studio Proper",
    "autorUrl": "https://unsplash.com/@studioproper",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/marco-de-plastico-redondo-blanco-sobre-mesa-negra-CWWa6f1EB5g",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "auraphone-destacado-3",
    "tipo": "foto",
    "media": "img/auraphone-destacado-3.webp",
    "descripcion": "auraPhone Duo abierto en tres cuartos sobre fondo negro, con dos apps lado a lado en su pantalla de 7,6 pulgadas: un mapa con la ruta y un chat",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPhone_Duo_fold.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla con dos apps en Split View generada por código; frontal enderezado y recompuesto en tres cuartos sobre negro."
  },
  {
    "slot": "auraphone-destacado-4",
    "tipo": "foto",
    "media": "img/auraphone-destacado-4.webp",
    "descripcion": "Gotas de agua sobre la pantalla de un auraPhone negro apoyado en una tarima de madera mojada",
    "autor": "Shuvro Mojumder",
    "autorUrl": "https://unsplash.com/@shuvrosettledown",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/telefono-inteligente-negro-sobre-superficie-de-madera-marron-d2Zc6G6y5H4",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "auraphone-destacado-5",
    "tipo": "foto",
    "media": "img/auraphone-destacado-5.webp",
    "descripcion": "Conector USB-C de un cable claro en primer plano, sobre fondo negro",
    "autor": "Mishaal Zahed (Meschael Zahède)",
    "autorUrl": "https://unsplash.com/@mishaalzahed",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/cable-usb-blanco-sobre-superficie-negra-dYocS1QjjvI",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "auraphone-diseno",
    "tipo": "foto",
    "media": "img/auraphone-diseno.webp",
    "descripcion": "auraPhone 18 Pro plata en diagonal sobre fondo negro: unibody de aluminio y meseta de cámaras",
    "autor": "Olgierd Rudak",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Olgierd_Rudak",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPhone_17_Pro_(2025-12-28).jpg",
    "licencia": "CC0",
    "licenciaUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "auraphone-duo",
    "tipo": "foto",
    "media": "img/auraphone-duo.webp",
    "descripcion": "auraPhone Duo blanco estelar, abierto y visto por detrás: doble cámara en una cápsula y la pantalla exterior apagada, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPhone_Duo_fold_rear.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "auraphone-foto-1",
    "tipo": "foto",
    "media": "img/auraphone-foto-1.webp",
    "descripcion": "Retrato de un gato atigrado de ojos azules con el fondo desenfocado en tonos cálidos",
    "autor": "AdinaVoicu",
    "autorUrl": "https://pixabay.com/users/adinavoicu-485024/",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Tabby_cat_with_blue_eyes-3336579.jpg",
    "licencia": "CC0",
    "licenciaUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "auraphone-foto-2",
    "tipo": "foto",
    "media": "img/auraphone-foto-2.webp",
    "descripcion": "Aurora boreal verde y roja sobre un lago en calma, con las luces de un pueblo reflejadas en el agua",
    "autor": "Nico Becker",
    "autorUrl": "https://www.pexels.com/@nicobecker",
    "fuente": "Pexels",
    "url": "https://www.pexels.com/photo/stunning-northern-lights-over-tranquil-lake-39666020/",
    "licencia": "Licencia de Pexels",
    "licenciaUrl": "https://www.pexels.com/license/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "auraphone-foto-3",
    "tipo": "foto",
    "media": "img/auraphone-foto-3.webp",
    "descripcion": "Margarita blanca cubierta de gotas de lluvia, en primer plano sobre un fondo verde oscuro",
    "autor": "Josie Weiss",
    "autorUrl": "https://unsplash.com/@scarlettweiss",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/una-flor-blanca-y-amarilla-con-gotas-de-agua-3lTuflBEeKM",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "auraphone-medio-ambiente",
    "tipo": "foto",
    "media": "img/auraphone-medio-ambiente.webp",
    "descripcion": "Campo de paneles solares al atardecer, con montañas en el horizonte",
    "autor": "Michael Pointner",
    "autorUrl": "https://unsplash.com/@pino_rumbero",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-gran-panel-solar-con-montanas-al-fondo-OZ0ZEAm_PbE",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "auraphone-zoom-1",
    "tipo": "foto",
    "media": "img/auraphone-zoom-1.webp",
    "descripcion": "Primer plano de la meseta de cámaras de un auraPhone plateado: tres objetivos, flash y LiDAR sobre negro",
    "autor": "jiale MA",
    "autorUrl": "https://www.pexels.com/@jiale-ma-177643434",
    "fuente": "Pexels",
    "url": "https://www.pexels.com/photo/close-up-of-smartphone-camera-lenses-on-black-36503099/",
    "licencia": "Licencia de Pexels",
    "licenciaUrl": "https://www.pexels.com/license/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "auraphone-zoom-2",
    "tipo": "foto",
    "media": "img/auraphone-zoom-2.webp",
    "descripcion": "Silueta de un faro con la linterna encendida al anochecer, sobre un horizonte naranja y un cielo azul oscuro",
    "autor": "Tim Foster",
    "autorUrl": "https://unsplash.com/@timberfoster",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/silueta-del-faro-al-atardecer-luyqrtZaWmg",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "auraphone-zoom-3",
    "tipo": "foto",
    "media": "img/auraphone-zoom-3.webp",
    "descripcion": "Parte superior de un auraPhone con la isla de la cámara frontal y la pantalla de bloqueo encendida: la hora sobre una aurora azul y violeta, sobre fondo negro",
    "autor": "Fujiphilm",
    "autorUrl": "https://unsplash.com/@fujiphilm",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-telefono-celular-con-una-pantalla-purpura-YhDDmc_nW80",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla de bloqueo de serie sustituida por una de auraOS generada por código; se conserva la isla de la cámara frontal."
  },
  {
    "slot": "auraphone-zoom-4",
    "tipo": "foto",
    "media": "img/auraphone-zoom-4.webp",
    "descripcion": "Interior de un teléfono desmontado, con la placa térmica de cobre y pasta azul sobre el procesador",
    "autor": "Sandeep",
    "autorUrl": "https://unsplash.com/@adeveloper79",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/smartphone-desmontado-que-revela-componentes-electronicos-internos-l1uzgDexxd4",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "inicio-acerca",
    "tipo": "foto",
    "media": "img/inicio-acerca.webp",
    "descripcion": "Fachada de cristal azul de un edificio de oficinas de noche, con varias plantas iluminadas en luz cálida",
    "autor": "Jahanzeb Ahsan",
    "autorUrl": "https://unsplash.com/@jahan_photobox",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/ventanas-de-edificios-de-oficinas-iluminadas-por-la-noche-Xqb8MqNS8hc",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "inicio-hero-aurabook",
    "tipo": "foto",
    "media": "img/inicio-hero-aurabook.webp",
    "descripcion": "auraBook Pro abierto en la oscuridad, con el teclado bañado por la luz rosa y azul de su pantalla",
    "autor": "SimonWaldherr",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:SimonWaldherr",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:Apple_MacBook_Pro_16%22_M2_Max.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla sustituida por un fondo generado."
  },
  {
    "slot": "inicio-hero-aurapad",
    "tipo": "foto",
    "media": "img/inicio-hero-aurapad.webp",
    "descripcion": "auraPad Pro tumbado en perspectiva sobre fondo negro, con la pantalla encendida: ondas de luz violetas",
    "autor": "Kyu3a",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:Kyu3a",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:M4_iPad_Pro_series_-_2.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": "Pantalla sustituida por un fondo AURA generado por código."
  },
  {
    "slot": "inicio-hero-auraphone",
    "tipo": "foto",
    "media": "img/inicio-hero-auraphone.webp",
    "descripcion": "auraPhone Duo abierto de frente, con un degradado azul y violeta en la pantalla interior, sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPhone_Duo_fold.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "inicio-novedad-aurabook-air",
    "tipo": "foto",
    "media": "img/inicio-novedad-aurabook-air.webp",
    "descripcion": "auraBook plateado flotando en el aire sobre fondo negro, visto desde abajo con la tapa abierta",
    "autor": "Dima Solomin",
    "autorUrl": "https://unsplash.com/@solomin",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-ordenador-apple-vuela-por-los-aires-8bgkFqrG-aQ",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true,
    "retoque": "Borrados la manzana de la tapa y el grabado de la base."
  },
  {
    "slot": "inicio-novedad-aurapad-air",
    "tipo": "foto",
    "media": "img/inicio-novedad-aurapad-air.webp",
    "descripcion": "Cuatro auraPad Air de espaldas en abanico sobre fondo negro: gris espacial, blanco estrella, púrpura y azul",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPad_Air_11-inch_(M2)_back_side_(20250525_154602).jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "inicio-novedad-camara",
    "tipo": "foto",
    "media": "img/inicio-novedad-camara.webp",
    "descripcion": "Meseta de tres cámaras de un auraPhone 18 Pro azul glacial, de espaldas sobre fondo negro",
    "autor": "茅野ふたば",
    "autorUrl": "https://commons.wikimedia.org/wiki/User:%E8%8C%85%E9%87%8E%E3%81%B5%E3%81%9F%E3%81%B0",
    "fuente": "Wikimedia Commons",
    "url": "https://commons.wikimedia.org/wiki/File:IPhone_18_Pro_rear.jpg",
    "licencia": "CC BY-SA 4.0",
    "licenciaUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "inicio-novedad-teleobjetivo",
    "tipo": "foto",
    "media": "img/inicio-novedad-teleobjetivo.webp",
    "descripcion": "Primer plano de la meseta de tres cámaras de un auraPhone 18 Pro negro, sobre fondo negro",
    "autor": "ubeyonroad",
    "autorUrl": "https://unsplash.com/@ubeyonroad",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/smartphone-negro-con-tres-lentes-de-camara-en-la-parte-posterior-zJ4XmQsZzMI",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true,
    "retoque": ""
  },
  {
    "slot": "inicio-trade-in",
    "tipo": "foto",
    "media": "img/inicio-trade-in.webp",
    "descripcion": "Un teléfono desmontado, con los componentes internos a la vista, sobre una mesa azul oscuro",
    "autor": "Sandeep",
    "autorUrl": "https://unsplash.com/@adeveloper79",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-smartphone-desmontado-con-sus-componentes-internos-expuestos-x243E3Re1Q4",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "seq-aurabook-intro",
    "tipo": "vídeo",
    "media": "img/seq/aurabook-intro/poster.webp",
    "descripcion": "auraBook Pro abierto de frente sobre fondo negro, con el teclado negro y la pantalla que se enciende con una aurora azul y violeta",
    "autor": "Arpit Brandings",
    "autorUrl": "https://www.pexels.com/@arpit-brandings-1363149455",
    "fuente": "Pexels",
    "url": "https://www.pexels.com/video/macbook-floating-video-mockup-26109748/",
    "licencia": "Licencia de Pexels",
    "licenciaUrl": "https://www.pexels.com/license/",
    "modificada": true,
    "retocada": true,
    "retoque": "Fondo y suelo llevados a negro y pantalla sustituida por un fondo auraOS generado por código; 120 fotogramas del clip."
  },
  {
    "slot": "seq-auraphone-intro",
    "tipo": "foto",
    "media": "img/seq/auraphone-intro/poster.webp",
    "descripcion": "auraPhone 18 Pro plata de espaldas sobre fondo negro: la meseta de tres cámaras de lado a lado, de cerca y después con el teléfono entero en diagonal",
    "autor": "jiale MA",
    "autorUrl": "https://www.pexels.com/@jiale-ma-177643434",
    "fuente": "Pexels",
    "url": "https://www.pexels.com/photo/modern-smartphone-with-advanced-camera-features-36503100/",
    "licencia": "Licencia de Pexels",
    "licenciaUrl": "https://www.pexels.com/license/",
    "modificada": true,
    "retocada": true,
    "retoque": "Logotipo de la trasera borrado y fondo llevado a negro; el movimiento de cámara y el barrido de luz de los 120 fotogramas se generan por código."
  },
  {
    "slot": "seq-demo",
    "tipo": "vídeo",
    "media": "img/seq/demo/poster.webp",
    "descripcion": "Volutas de humo azulado que se arremolinan sobre un fondo negro",
    "autor": "Miguel Á. Padriñán",
    "autorUrl": "https://www.pexels.com/@padrinan",
    "fuente": "Pexels",
    "url": "https://www.pexels.com/video/close-up-shot-of-smoke-on-a-black-background-4320606/",
    "licencia": "Licencia de Pexels",
    "licenciaUrl": "https://www.pexels.com/license/",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "soporte-contacto",
    "tipo": "foto",
    "media": "img/soporte-contacto.webp",
    "descripcion": "Vista cenital de un especialista que atiende a un cliente junto a una mesa de madera clara con un auraPad expositor",
    "autor": "amandazi photography",
    "autorUrl": "https://unsplash.com/@amandazi_photography",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-empleado-de-tienda-ayuda-a-un-cliente-en-un-mostrador-DUWvgrJ2P-8",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": true,
    "retoque": "Borradas las manzanas de la bolsa, del jersey y de la tarjeta."
  },
  {
    "slot": "trade-in-hero",
    "tipo": "foto",
    "media": "img/trade-in-hero.webp",
    "descripcion": "El módulo de triple cámara de un auraPhone negro nuevo asoma de su caja abierta, sobre fondo negro",
    "autor": "Rohan Krishnan",
    "autorUrl": "https://unsplash.com/@rohankrishnann",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/un-iphone-en-una-caja-sobre-un-fondo-negro-lkizfYW3ohw",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  },
  {
    "slot": "trade-in-reciclaje",
    "tipo": "foto",
    "media": "img/trade-in-reciclaje.webp",
    "descripcion": "Un teléfono abierto deja ver el chasis, la batería y los circuitos, sobre una superficie oscura",
    "autor": "Sandeep",
    "autorUrl": "https://unsplash.com/@adeveloper79",
    "fuente": "Unsplash",
    "url": "https://unsplash.com/es/fotos/componentes-internos-de-un-smartphone-desmontado-sobre-una-superficie-oscura--PZRsFHDQQk",
    "licencia": "Licencia de Unsplash",
    "licenciaUrl": "https://unsplash.com/license",
    "modificada": true,
    "retocada": false,
    "retoque": ""
  }
];
